In [1]:
import pandas as pd
import requests

In [2]:
path = "https://en.wikipedia.org/wiki/list_of_postal_codes_of_Canada:_M"
info = requests.get(path).content 

df = pd.read_html(info, header=0)[0]
df.head()

  Post Code           Borough               Neighborhood
0       M1A      Not assigned               Not assigned
1       M2A      Not assigned               Not assigned
2       M3A        North York                  Parkwoods
3       M4A        North York           Victoria Village
4       M5A  Downtown Toronto  Regent Park, Harbourfront

In [3]:
df_tor=df[df.Borough != "Not assigned"]
df_tor.head()

  Post Code           Borough                                 Neighborhood
2       M3A        North York                                    Parkwoods
3       M4A        North York                             Victoria Village
4       M5A  Downtown Toronto                    Regent Park, Harbourfront
5       M6A        North York             Lawrence Manor, Lawrence Heights
6       M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [5]:
df_tor[df_tor.Neighborhood == "Not assigned"]

df_tor = df_tor.drop_duplicates()
df_tor.head()

  Post Code           Borough                                 Neighborhood
2       M3A        North York                                    Parkwoods
3       M4A        North York                             Victoria Village
4       M5A  Downtown Toronto                    Regent Park, Harbourfront
5       M6A        North York             Lawrence Manor, Lawrence Heights
6       M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [17]:
df_tor.rename(columns = {"Post Code":"PostalCode"} , inplace = True)
df_tor.reset_index(inplace= True, drop= True)
df_tor.head(12)

   PostalCode  ...                                       Neighborhood
0         M3A  ...                                          Parkwoods
1         M4A  ...                                   Victoria Village
2         M5A  ...                          Regent Park, Harbourfront
3         M6A  ...                   Lawrence Manor, Lawrence Heights
4         M7A  ...        Queen's Park, Ontario Provincial Government
5         M9A  ...            Islington Avenue, Humber Valley Village
6         M1B  ...                                     Malvern, Rouge
7         M3B  ...                                          Don Mills
8         M4B  ...                    Parkview Hill, Woodbine Gardens
9         M5B  ...                           Garden District, Ryerson
10        M6B  ...                                          Glencairn
11        M9B  ...  West Deane Park, Princess Gardens, Martin Grov...

[12 rows x 3 columns]

In [18]:
path = "https://cocl.us/Geospatial_data"
df_path = pd.read_csv(path)
df_path.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [19]:
df = df_tor.join(df_path.set_index("Postal Code"), on='PostalCode')
df.head()

  PostalCode           Borough  ...   Latitude  Longitude
0        M3A        North York  ...  43.753259 -79.329656
1        M4A        North York  ...  43.725882 -79.315572
2        M5A  Downtown Toronto  ...  43.654260 -79.360636
3        M6A        North York  ...  43.718518 -79.464763
4        M7A  Downtown Toronto  ...  43.662301 -79.389494

[5 rows x 5 columns]

In [21]:
df

    PostalCode           Borough  ...   Latitude  Longitude
0          M3A        North York  ...  43.753259 -79.329656
1          M4A        North York  ...  43.725882 -79.315572
2          M5A  Downtown Toronto  ...  43.654260 -79.360636
3          M6A        North York  ...  43.718518 -79.464763
4          M7A  Downtown Toronto  ...  43.662301 -79.389494
..         ...               ...  ...        ...        ...
98         M8X         Etobicoke  ...  43.653654 -79.506944
99         M4Y  Downtown Toronto  ...  43.665860 -79.383160
100        M7Y      East Toronto  ...  43.662744 -79.321558
101        M8Y         Etobicoke  ...  43.636258 -79.498509
102        M8Z         Etobicoke  ...  43.628841 -79.520999

[103 rows x 5 columns]

In [22]:
df.head(12)

   PostalCode           Borough  ...   Latitude  Longitude
0         M3A        North York  ...  43.753259 -79.329656
1         M4A        North York  ...  43.725882 -79.315572
2         M5A  Downtown Toronto  ...  43.654260 -79.360636
3         M6A        North York  ...  43.718518 -79.464763
4         M7A  Downtown Toronto  ...  43.662301 -79.389494
5         M9A         Etobicoke  ...  43.667856 -79.532242
6         M1B       Scarborough  ...  43.806686 -79.194353
7         M3B        North York  ...  43.745906 -79.352188
8         M4B         East York  ...  43.706397 -79.309937
9         M5B  Downtown Toronto  ...  43.657162 -79.378937
10        M6B        North York  ...  43.709577 -79.445073
11        M9B         Etobicoke  ...  43.650943 -79.554724

[12 rows x 5 columns]